# Default values for demotest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: yogeshraheja/devopsinaction
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2"

service:
  type: NodePort
  port: 80
  nodePort: 31666
